### ISSUE TITLE
Connect to localhost?

### ISSUE THREAD

**Issue by bbbush** [isen-ng/testcontainers-dotnet#44]
Hi-

I have Docker Desktop (2.2.0.3) installed on Windows 10 (Hyper-V), and was running the sample unit test from vs2019. At first the unit test code was not able to connect to the Ryuk container; when disabled that with REAPER_DISABLED=1, the unit test code was not able to connect to the SQLServer container.

When I traced code, I found that the code constructed a connection string using container's IP address? https://github.com/isen-ng/testcontainers-dotnet/blob/61035b234260ec536a26324f35f25856430c7e00/src/Container.Abstractions/AbstractContainer.cs#L436 has very different logic from https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/src/DotNet.Testcontainers/Containers/Modules/TestcontainersContainer.cs#L73 and https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L61

I suppose the intention is to have all unit tests run within a container? But that is not convenient if running on Windows without the well defined CI environment.

Thanks!

**Comment by isen-ng** [comment]
Thank you for raising this bug.

I believe this arises due to the classic way docker desktop for windows provisions linux containers.

They provision containers in a moby linux VM, and I believe the resulting gateway network interface, is only available in the linux VM and is not available from windows. This code works in an linux and mac environment.

I believe I know a fix for this. Unfortunately, I will only have access to my Windows desktop during weekends, so I can only test this fix and publish a new version this weekend.
