### ISSUE TITLE
TestContainer on Windows env

### ISSUE THREAD

**Issue by AndersLindPedersen** [isen-ng/testcontainers-dotnet#57]
I have a need to move from a linux environment to a windows due to other dependencies during testing in our pipelines.

But running my current test gives we an error:

`_container = new ContainerBuilder<PostgreSqlContainer>()
                .ConfigureDockerImageName("postgres:11-alpine")
                .ConfigureContainer((h, c) => { c.PortBindings.Add(PostgreSqlContainer.DefaultPort, 5433); })
                .Build();`

I get the following error:

![image](https://user-images.githubusercontent.com/33549391/121347303-53193300-c927-11eb-969b-9c665480e5ec.png)

**Comment by isen-ng** [comment]
Hello @AndersLindPedersen 

Thank you for raising the issue. I just verified that this docker image, `quay.io/testcontainers/ryuk:0.2.3` still [exists](https://quay.io/repository/testcontainers/ryuk?tab=tags).

However, I suspect that you cannot pull this image because your docker desktop client is set to run/pull only Windows based containers.

Switch to linux containers to fix this problem:

![image](https://user-images.githubusercontent.com/3904043/121455105-836bda80-c9d6-11eb-9a7c-757e87dd8d6f.png)

**Comment by AndersLindPedersen** [comment]
This is actually running on Azure DevOps build agents, with Windows OS.

**Comment by isen-ng** [comment]
Sorry for the late response!

I'm not familiar with Azure devops, but I'm assuming you MUST compile your code using Windows?

The current version of this library doesn't support running windows-based containers. This library can run on Windows OS, but the containers should still be linux based. That means the docker on the Windows OS should be running linux containers.

Does this fit your use-case? Are you running Windows-based containers, or linux-based containers.

**Comment by isen-ng** [comment]
If indeed you are using linux based containers in your Windows OS, then you need to use a azure devops image that supports this.

In your azure pipelines yaml file, there should be somewhere for you to define the image to use to run your pipeline. You need to select an image that suits your needs. E.G. A windows OS image with linux-based docker installed

**Comment by AndersLindPedersen** [comment]
We solved this by running on linux build agents. ;)
